### PR TITLE
Be more defensive when reading file meta

### PR DESCRIPTION
**Pull request by m-vdb**
**Proposed changes**

If the "meta" doesn't conform to the expected format, skip the file altogether.

- [x] added tests

### CODE REVIEW

**Comment by unlight** [comment]
Is this PR ready?

**Comment by unlight** [comment]
Changes are ok. But commit messages are not conventional https://www.conventionalcommits.org/en/v1.0.0/#summary

**Comment by m-vdb** [comment]
hello @unlight 👋 PR is ready (unless I missed some steps). Happy to reword the commits!

**Comment by m-vdb** [comment]
there you go @unlight 😄

**Pull request merged**
